spring:
  application:
    name: ppoo
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081

scalar:
  path: "/scalar/"