spring.application.name=tutoria002
server.port=8089
spring.datasource.url=jdbc:mysql://localhost:3306/tutoria004
spring.datasource.username=ppoo
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update